### PR TITLE
update PusherSwift SDK to 8.0.0

### PR DESCRIPTION
**Pull request by tshedor**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Xcode 12.5 can't compile a component of CryptoSwift. This PR updates the SDK to remove the CryptoSwift dependency.

It does not update to the latest SDK (9.2.2) because that update enforces the minimum deployment target of iOS 13. There should be an intermediate version (this PR) before forcing the upgrade to 13.

### :arrow_heading_down: What is the current behavior?

Can't build in Xcode 12.5

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/ninjasolutions/flutter_pusher/blob/master/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by tshedor** [comment]
Hey @genert friendly nudge on this PR

**Comment by soewaiyanmyowin** [comment]
It works for me ! Thanks in advance . Really appreciate your effort.

**Comment by ziggycrane** [comment]
Does not work. The error I get now:
CryptoSwift/Sources/CryptoSwift/Generics.swift:35:28: error: 'exported: true' has no effect in '_specialize' attribute
    @_specialize(exported: true, where T == Int)

**Comment by genert** [comment]
LGTM

**Review by genert — APPROVED** [review]
